# Source preparation pipeline to be run from mapterhorn/pipelines folder
[no-cd]
default:
    uv run python source_download.py aatw
    uv run python source_unzip.py aatw
    uv run python source_bounds.py aatw
    uv run python source_polygonize.py aatw 32
    uv run python source_create_tarball.py aatw